name: advanced_calendar_day_view
description: This package is dedicated to calendar day view. This is a complement to calendar to make your app better
version: 3.3.3
homepage: https://github.com/samderlust/calendar_day_view

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

topics:
  - calendar
  - calendar-day-view
  - calendar-view
  - day-view
